site_name: updatehub Documentation
site_description: 'All your devices, always updated.'
site_url: !!python/object/apply:os.getenv ["SITE"]
site_favicon: assets/images/favicon.ico
copyright: 'Copyright © 2017 O.S. Systems'
theme: material
theme_dir: theme
markdown_extensions:
  - markdown.extensions.codehilite
  - markdown.extensions.admonition
  - markdown.extensions.def_list
extra:
  logo: assets/images/logo.png
  font:
    text: 'Fira Sans'
  social:
    - type: globe
      link: https://updatehub.io
    - type: 'github'
      link: 'https://github.com/updatehub'
pages:
  - Welcome: index.md
  - Getting Started:
    - What is updatehub?: getting-started/what-is-updatehub.md
  - Advanced:
    - updatehub Agent:
      - Overview: advanced/updatehub-agent/overview.md
