site_name: updatehub Documentation
site_description: 'All your devices, always updated.'
site_url: !!python/object/apply:os.getenv ["SITE"]
site_favicon: assets/images/favicon.ico
copyright: 'Copyright © 2017 O.S. Systems'
theme: material
theme_dir: theme
markdown_extensions:
  - markdown.extensions.codehilite
  - markdown.extensions.admonition
  - markdown.extensions.def_list
extra:
  logo: assets/images/logo.png
  font:
    text: 'Fira Sans'
  social:
    - type: globe
      link: https://updatehub.io
    - type: 'github'
      link: 'https://github.com/updatehub'
pages:
  - Welcome: index.md
  - Overview: overview.md
  - Quick Start: quick-start.md
  - Yocto Integration:
    - Overview: yocto-integration/overview.md
    - BSP Layers: yocto-integration/bsp-layers.md
    - Image Classes: yocto-integration/image-classes.md
  - Advanced:
    - updatehub Agent:
      - Overview: advanced/updatehub-agent/overview.md
      - Configuration: advanced/updatehub-agent/configuration.md
      - Device Identity Scripts: advanced/updatehub-agent/device-identity-scripts.md
      - Callback Scripts: advanced/updatehub-agent/callback-scripts.md
    - updatehub Utilities (uhu):
      - Overview: advanced/uhu/overview.md
      - Getting Started: advanced/uhu/getting-started.md
      - Creating an update package: advanced/uhu/creating-update-package.md
